version: '3.8'

services:
  # Microservice order-service
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quickbite-order-service
    ports:
      - "8686:8686"
    networks:
      - quickbite-net

  # Prometheus Server
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: quickbite-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - quickbite-net

  # Node Exporter cho giám sát phần cứng VPS Host
  node-exporter:
    image: prom/node-exporter:v1.6.0
    container_name: quickbite-node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    networks:
      - quickbite-net

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:10.0.3
    container_name: quickbite-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin123
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - quickbite-net
    depends_on:
      - prometheus

networks:
  quickbite-net:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
